= Spring Boot v3.2 Rest Clients demo


== Running as JAR

 ./gradlew assemble
 java -jar build/libs/rest-clients-native-0.0.1-SNAPSHOT.jar

Expected output

----
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::            (v3.2.0-RC2)

. . .

Calling Star Wars API:
  Planet found: Tatooine
  Planet found: Alderaan
  Planet found: Yavin IV
  Planet found: Hoth
  Planet found: Dagobah
  Planet found: Bespin
  Planet found: Endor
  Planet found: Naboo
  Planet found: Coruscant
  Planet found: Kamino
----

[[native-build]]
== Running as Native Image

 ./gradlew nativeCompile
 ./build/native/nativeCompile/rest-clients-native

== Known issues

=== Rest Clients not able to deserialize JSON response

When calling the StarWars endpoint, the following error appears:

----
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `com.example.clients.sw.PlanetsList`: cannot deserialize from Object value (no delegate- or property-based Creator): this appears to be a native image, in which case you may need to configure reflection for the class that is to be deserialized
 at [Source: (org.springframework.util.StreamUtils$NonClosingInputStream); line: 1, column: 2]
        at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1915) ~[rest-clients-native:2.15.3]
        at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:414) ~[rest-clients-native:2.15.3]
        at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1355) ~[rest-clients-native:2.15.3]
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1421) ~[rest-clients-native:2.15.3]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:352) ~[rest-clients-native:2.15.3]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185) ~[rest-clients-native:2.15.3]
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323) ~[rest-clients-native:2.15.3]
        at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:2105) ~[rest-clients-native:2.15.3]
        at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1481) ~[rest-clients-native:2.15.3]
        at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:395) ~[rest-clients-native:6.1.0-RC2]
        ... 21 common frames omitted
----

To reproduce, build image and <<run,native-build>> or run tests in native `./gradlew nativeTest`.

[[json-fixes]]
==== Fixes found

IMPORTANT: Solutions work for binaries in Linux.
For MacOs test the app via OCI image with `bootBuildImage`.

1. Configure `@RegisterReflectionForBinding` with the required classes
+
----
@RegisterReflectionForBinding({PlanetsList.class, Planet.class}) in RestClientsNativeApplication
public class RestClientsNativeApplication
----
+
This works for app, but not for tests.
To run tests, they need to be run with `@SpringBootTest` which makes them start slower.

2. Add `reflect-config.json` with metadata for required classes.
The JSON contents can be obtained from the generated file (`./build/resources/aot/META-INF/native-image/com.example/rest-clients-native/reflect-config.json`) by Spring Boot native tools and placed in `/src/main/resources/META-INF/native-image/com.example/rest-clients-native/`.

+
This works for both app and tests (Linux & MacOS), but it's obviously more cumbersome and requires more maintenance effort.


=== Rest client not able to serialize JSON for requests

----
Failures (1):
  JUnit Jupiter:PostsClientTest:shouldListPlanets()
    MethodSource [className = 'com.example.clients.PostsClientTest', methodName = 'shouldListPlanets', methodParameterTypes = '']
    => org.springframework.web.client.RestClientException: No HttpMessageConverter for com.example.clients.posts.PostRequest and content type "application/json"
       org.springframework.web.client.DefaultRestClient$DefaultRequestBodyUriSpec.writeWithMessageConverters(DefaultRestClient.java:358)
       org.springframework.web.client.DefaultRestClient$DefaultRequestBodyUriSpec.lambda$body$0(DefaultRestClient.java:317)
       org.springframework.web.client.DefaultRestClient$DefaultRequestBodyUriSpec.exchangeInternal(DefaultRestClient.java:404)
       org.springframework.web.client.DefaultRestClient$DefaultRequestBodyUriSpec.retrieve(DefaultRestClient.java:380)
       com.example.clients.posts.PostsClient.create(PostsClient.java:22)
       com.example.clients.PostsClientTest.shouldListPlanets(PostsClientTest.java:20)
       java.base@21.0.1/java.lang.reflect.Method.invoke(Method.java:580)
       java.base@21.0.1/java.util.ArrayList.forEach(ArrayList.java:1596)
       java.base@21.0.1/java.util.ArrayList.forEach(ArrayList.java:1596)
----

==== Fix

The message is different and miss-leading but the underlying issue can be fixed with the same solutions as <<json-fixes,above>>.

For reference, this is the full annotated configuration.

[,java]
.Application class configuration
----
@RegisterReflectionForBinding({PlanetsList.class, Planet.class, PostRequest.class, PostResponse.class})
----
